services:
  ubuntu:
    container_name: ubuntu_server
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./data:/app
    tty: true
    ports:
      - "8888:8888" # jupyter labを接続するため
